DROP TABLE IF EXISTS SYSTEM_USER;
CREATE TABLE SYSTEM_USER(
  ID        NUMBER(10) not null primary key,
  USER_NAME VARCHAR(10),
  MOBILE    NUMBER(11),
  OPERATOR  VARCHAR(10),
  CREATE_TIME    DATE,
  UPDATE_TIME    DATE
);
